### ISSUE TITLE
Show username instead of profile name

### ISSUE THREAD

**Issue by davehakkens** [hakkens/davehakkens#1]
![Uploading username.jpg…]()
In our forums we want to show peoples username instead of their profile name. Making it easier for people the @include or @reply another member.

**Comment by marcoherremans** [comment]
When you go to your profile settings you can choose your public display name to be your: first name, last name, first and last name or username. Now the standard is first-last name, but this can be changed in the code. Unfortunately I can only edit your theme codes and not your wordpress codes here, on reddit, but here are some instructions on how to do it here; https://wordpress.org/search/Default+Displayname

(Most of these explain how you can chance the default username to first-last name, but you can do this the other way around)

**Comment by davehakkens** [comment]
I think you can also do this customizing the BBpress templates. (which are in the Github.) Tried this topic before: https://bbpress.org/forums/topic/showing-username-beneath-display-name/ The @username showed up. However I wasn't able to replace it with the name. It just showed the username underneath the name. But it seems like a good startingpoint

**Comment by marcoherremans** [comment]
Ow, yes, that's also a possibility, then you only change the name displayed on the forum and not the name on the whole website. 
-------
When you go to: "bbpress/loop-single-reply.php" - "line 16", you can chance the display settings using this: "https://codex.bbpress.org/bbp_reply_author_link". 
When you turn the display name off there, and use the code you already used, its solved.

**Comment by davehakkens** [comment]
Hi thanks for that. Have been playing around with this snippet.
  <div class="author">
    <?php do_action( 'bbp_theme_before_reply_author_details' ); ?>
    <?php bbp_reply_author_link( array( 'sep' => '<br />', 'show_role' => false, 'type' => 'name' ) ); ?>
    <?php $user = get_userdata( bbp_get_reply_author_id() );
if ( !empty( $user->user_nicename ) ) {
$user_nicename = $user->user_nicename;
echo "@".$user_nicename;
} ?>
    <?php do_action( 'bbp_theme_after_reply_author_details' ); ?>
  </div>

But can't seem to to get it correctly.  Keep ending up with weird layouts and still the name.
You know which exact code will work?

![schermafbeelding 2015-10-19 om 10 07 06](https://cloud.githubusercontent.com/assets/13672737/10572745/3d74332c-764b-11e5-842b-b290af7eb423.png)

**Comment by marcoherremans** [comment]
Maybe it's that you forgot the '<br />' after array( 'sep' =>   :smile:.

if that doesn't work out (but i think it does) you can try this code:

 <div class="author">
 <?php do_action( 'bbp_theme_before_reply_author_details' ); ?>
 <?php bbp_reply_author_link( array( 'sep' => '<br />', 'show_role' => false, 'type' => 'avatar' ) ); ?>
 <?php do_action( 'bbp_theme_after_reply_author_details' ); ?>
<?php $user = get_userdata( bbp_get_reply_author_id() );
if ( !empty( $user->user_nicename ) ) {
$user_nicename = $user->user_nicename;
echo "@".$user_nicename;
} ?>
  </div>

**Comment by davehakkens** [comment]
Awesome! Your code does the job.
1:  Is it possible to put the "rank" underneath the username (now the rank comes first)
2: Can we link both @username and avatar to the member/profile page, instead of member/activity?
