### ISSUE TITLE
Remove 'reply to'  in forum titles

### ISSUE THREAD

**Issue by davehakkens** [hakkens/davehakkens#10]
for some reasons a lot of topics get the words 'reply to:' before the title. 
Not sure when or how it happens but since the last 2 weeks it has been popping up

![image](https://cloud.githubusercontent.com/assets/13672737/11786309/1d0204b8-a286-11e5-8284-52b7cd9d7dc6.png)

**Comment by leo** [comment]
Can you take a look into the address bar and add the link here? Because I think WP is assuming that you're replying to a certain comment.

**Comment by davehakkens** [comment]
https://davehakkens.nl/community/forums/topic/vote-logo/
https://davehakkens.nl/community/forums/topic/read-before-you-help/
https://davehakkens.nl/community/forums/topic/its-time-for-a-recap-a-phone-worth-keeping/

**Comment by leo** [comment]
Looks like it's not the fault of a URL parameter. So it should be investigated! :blush:
