### ISSUE TITLE
Add moderator badges

### ISSUE THREAD

**Issue by davehakkens** [hakkens/davehakkens#20]
We use the Mycred plugin for our member rankings and badges. Currently all badges of a member are shown in its member profile at the bottom. We also need certain badges to be displayed within the forums itself. The moderator and the team badge. To easily recognize
 a moderator or forum member. Mycred contains many hooks to use.
Below a little image of what we need to achieve. 
![add badges](https://cloud.githubusercontent.com/assets/13672737/26681219/a9498eea-46dc-11e7-9d8f-3ad9da6f8e01.jpg)

Mycred: https://mycred.me/ - https://wordpress.org/plugins/mycred/

**Comment by alromh87** [comment]
Done @ https://github.com/alromh87/davehakkens/commit/3f64bb79e713d9b2275083dc2da44b5dc38c80fc

![captura de pantalla de 2017-06-23 01-14-38](https://user-images.githubusercontent.com/7505980/27469080-3a7cfe06-57b3-11e7-9f65-cb15a7a69504.png)
![captura de pantalla de 2017-06-23 01-14-50](https://user-images.githubusercontent.com/7505980/27469079-3a7a9990-57b3-11e7-9b36-ca9b97e02329.png)

**Comment by alromh87** [comment]
![captura de pantalla de 2017-06-23 02-50-15](https://user-images.githubusercontent.com/7505980/27472360-9e699d90-57c0-11e7-961d-b5a47400ca05.png)

**Comment by Jerzeek** [comment]
Still some problems with the styling...
http://imgur.com/a/tBfYz

**Comment by Jerzeek** [comment]
sorry, im a retard, had an old styles in memory....
