### ISSUE TITLE
Overlap on mobile

### ISSUE THREAD

**Issue by mattia-io** [hakkens/davehakkens#24]
![image uploaded from ios 1](https://user-images.githubusercontent.com/17761877/27172203-ac2faf30-51b4-11e7-831e-cbcc2cf352ed.jpg)
![image uploaded from ios](https://user-images.githubusercontent.com/17761877/27172202-ac2eb094-51b4-11e7-8da4-cd4376cf481e.jpg)

**Comment by davehakkens** [comment]
fixed in 2.3 🔥
