### ISSUE TITLE
Portrait Forum images are shown landscape

### ISSUE THREAD

**Issue by davehakkens** [hakkens/davehakkens#25]
Portrait Images that are uploaded in the forums by a user are automatically rotated 90 degrees into landscape. They should not be rotated. (top image is shown wrong) 
![image](https://user-images.githubusercontent.com/13672737/27205951-49d74804-5234-11e7-8c6e-f83adf3e145d.png)

We use the "GD bbPress Attachments" plugin for attachments
https://wordpress.org/plugins/gd-bbpress-attachments/

**Comment by MaloRchrd** [comment]
So i found a start of an issue but i can't try it as i didn't been able to set the forum properly on my local machine (i think this should also be added to the ReadMe as it is a pain) 

here is the answer i found 
Maybe try it out on the dev site ;-) 
[gist fix ](https://gist.github.com/n7studios/6a764d46bc1d515ba406)

**Comment by davehakkens** [comment]
haha yeh, quite a hassle to run locally. mainly all the little configurations and settings. I can invite you as an admin to the dev site so you can play around?

**Comment by MaloRchrd** [comment]
sure please do so so i can try this plugin aswell. https://wordpress.org/plugins/fix-image-rotation/

**Comment by davehakkens** [comment]
any luck @MaloRchrd?

**Comment by MaloRchrd** [comment]
@davehakkens, 
Sorry didn't had some spare time yet for this one. The thing is as I can't deploy the forum locally (or need more time to understand how it is set up) I can't try without it. And de dev environment I can't access the code that's why I suggested the plugin. Maybe I ll get a bit of time this weekend.

**Comment by MaloRchrd** [comment]
If your in a rush for version 2.3 I think you can copy and paste this in the function.php
I didn't tried it but the code looks good.


 https://gist.github.com/n7studios/6a764d46bc1d515ba406

**Comment by davehakkens** [comment]
Ok thanks. no worries I’ll give that code a try. But I think we broke the
image uploader so first need to fix that :D


On 2 March 2018 at 00:24:44, MaloRchrd (notifications@github.com) wrote:

If your in a rush for version 2.3 I think you can copy and paste this in
the function.php
I didn't tried it but the code looks good.

https://gist.github.com/n7studios/6a764d46bc1d515ba406

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hakkens/davehakkens/issues/25#issuecomment-369808817>,
or mute the thread

**Comment by davehakkens** [comment]
WORKS :D 🍡

**Comment by MaloRchrd** [comment]
Great 👌
