### ISSUE TITLE
Sign up button is hidden

### ISSUE THREAD

**Issue by mattia-io** [hakkens/davehakkens#29]
Users are trying to signup to DH account but can't confirm sign up as the button seems to be hidden

https://davehakkens.nl/community/register/

<img width="1139" alt="screen shot 2017-07-04 at 12 30 06" src="https://user-images.githubusercontent.com/17761877/27826822-e1cf9592-60b4-11e7-8ce4-ed4d1ba45512.png">
<img width="1373" alt="screen shot 2017-07-04 at 12 30 15" src="https://user-images.githubusercontent.com/17761877/27826823-e1cfd4f8-60b4-11e7-82e1-040ead71d8c7.png">

**Comment by davehakkens** [comment]
fixed
