### ISSUE TITLE
Make embeded videos in forums full width

### ISSUE THREAD

**Issue by davehakkens** [hakkens/davehakkens#5]
Make the width of embedded (youtube) videos always 100% width, also on mobile.
<img width="920" alt="schermafbeelding 2015-10-18 om 01 31 26" src="https://cloud.githubusercontent.com/assets/13672737/10561756/c081b49c-7538-11e5-8f1f-b30d59e90339.png">

**Comment by marcoherremans** [comment]
I think a CSS will help, I don't know if you have already used css somewhere, but if you didn't you can easily use CSS with a plugin like https://nl.wordpress.org/plugins/simple-custom-css/. 

There you can experiment or play with a couple of CSS codes like this one:

iframe {
  width: 100%;
}

which (should) make every iframe 100% width 
or you can add a height to it like this:

iframe {
  width: 100%;
 height: 50%;
}

or

iframe {
  width: 100%;
 height: auto;
}

or if you want all videos 100% 

video {
	max-width: 100%;
	height: auto;
}

or you can do this with iframes, videos and images

iframe, video, img {
  max-width: 100%;
  min-height: auto;
}

**Comment by davehakkens** [comment]
Thanks for that. Should be fixed! Also, i'm pretty familiar with CSS,  not with PHP. At all.
