### ISSUE TITLE
links in forum posts are sometimes not clickable

### ISSUE THREAD

**Issue by zzanzare** [hakkens/davehakkens#61]
It seems that whenever a link uses a text label instead of the full URL, the link becomes broken and doesn't actually do anything when clicked. At least I see it that way on mobile (android) with one outdated chrome and one up-to-date firefox.

Example: 
https://davehakkens.nl/community/forums/topic/developer-help-out-but-how/ (link in first post is clickable, link in reply is not)

The main suspect after looking at the html source code is the `rel="noopener"` tag.

**Comment by davehakkens** [comment]
should be fixed now 🙏
[watch commit](https://github.com/hakkens/davehakkens/commit/62a0e0ce391fbad30cd4c0524b1f1cd182e8ed72)
