### ISSUE TITLE
CSS : select fields in edit profile screen

### ISSUE THREAD

**Issue by ARMBouhali** [hakkens/davehakkens#70]
Height of Birthday select fields (Year/Month/Day) are not displayed correctly in an updated google chrome browser.

![birthday edit not displayed correctly](https://user-images.githubusercontent.com/10594967/33186717-0e9436f4-d08c-11e7-8f64-541edde317f5.png)

**Solution :** 
in style.css line 3262 edit height and replace this : 
`.profile-edit select {
   height: 40px!important;
}`

with that : 
`.profile-edit select {
   height: 58px!important;
}`

**Comment by davehakkens** [comment]
fixed in 2.3 :)
