### ISSUE TITLE
Fix styling in sidebar 

### ISSUE THREAD

**Issue by davehakkens** [hakkens/davehakkens#9]
Fix styling of 'popular links' in sidebar on large screens.

![image](https://cloud.githubusercontent.com/assets/13672737/11786215/b18851a6-a285-11e5-864f-c638810c2325.png)

**Comment by leo** [comment]
Where is this located?

**Comment by davehakkens** [comment]
on the right side if you scale your screen. (imac) 
![image](https://cloud.githubusercontent.com/assets/13672737/11864218/06af2e36-a49b-11e5-83bd-08bdb18c6000.png)
