### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by mattia-io** [hakkens/davehakkens#95]
Some misalignment here on chrome 
<img width="871" alt="screen shot 2018-05-28 at 10 12 55" src="https://user-images.githubusercontent.com/17761877/40604693-3c83a570-6260-11e8-898c-c7a7d6db64a5.png">

**Comment by MaloRchrd** [comment]
@mattia-io  Coud you give the link in order to check when the bug happen ;-)

**Comment by MaloRchrd** [comment]
Ok i found where it was happening, 

It a super weird behavior that is quite hard to understand anyway a quick fix is to remove the forced font size of 14px and leave it to the classic 18px (cf: screenshot). 

<img width="1174" alt="capture d ecran 2018-05-29 a 12 27 41" src="https://user-images.githubusercontent.com/17042850/40638118-e0cade10-633b-11e8-8384-8f9b98640a1b.png">


It is on line 4298 on the website css  but it's on line [4039](https://github.com/hakkens/davehakkens/blob/master/style.css#L4039) on the github file style.css 

All you have to do is remove [the line 4041 ](https://github.com/hakkens/davehakkens/blob/master/style.css#L4041)

**Comment by mattia-io** [comment]
Hey man.. thanks for looking into this :)
I guess the problem is site wide. 

Cool, thanks for spotting it!
M

**Comment by davehakkens** [comment]
fixed. `<div class="comments"> `was missing on certain templates
